### ISSUE TITLE
Old readme did not work

### ISSUE THREAD

**Issue by Damianuscz** [715209/gps-logger#1]
Hello i have 2 problems with replicate your great appt.

First 1. here.com
did not use APP ID and APP CODE in REST. So i must use APP ID and APP CODE from HERE SDK FOR ANDROID ???

Second 2. problem is in GPSLogger app...
whe i use HTTP send app say: cleartext communication not permitted by network security policy
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

I think it is problem of newest android and security policy.

Sorry for my bad english.

**Comment by b3ck** [comment]
1.) You have to use the 'JS REST' APP ID & APP CODE, no other id/code will work from HERE.com.
2.) I have a Samsung S10e with the latest software and security updates, I have no issues.

Double check your settings in Android, and in the app.  Make sure all of your ports are open, make sure you are not on the same network etc..

**Comment by b3ck** [comment]
Updated: https://github.com/715209/gps-logger/releases/tag/v3.0.0

Download, start fresh.
