### ISSUE TITLE
No app code

### ISSUE THREAD

**Issue by Ladelltwitch** [715209/gps-logger#3]
https://i.imgur.com/48uqKN2.png

https://i.imgur.com/dSqafah.png
[App Code Credentials
App code credentials will continue to be supported for a few products and current Developer Portal accounts where App code credentials have already been generated for an App. New accounts will only be able to use App Code credentials for some legacy products. App code credentials are the least secure of the authentication credential types and we recommend the use of the API Key or OAuth 2.0 Token credentials instead for improved security.]

**Comment by UnisonRU** [comment]
I have the same problem.

**Comment by UnisonRU** [comment]
@715209 @b3ck can you fix this please?

**Comment by b3ck** [comment]
On it.

**Comment by b3ck** [comment]
Updated: https://github.com/715209/gps-logger/releases/tag/v3.0.0

Download, start fresh.
